/* crispy-profiler-private.h - Profiling utilities (private) */

/*
 * Copyright (C) 2025 Zach Podbielniak
 *
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

/*
 * Private helpers for compiling scripts with -pg profiling
 * instrumentation and post-processing the resulting gmon.out
 * file with gprof.  This header is NOT installed or included
 * in the public umbrella header.
 */

#ifndef CRISPY_PROFILER_PRIVATE_H
#define CRISPY_PROFILER_PRIVATE_H

#include <glib.h>

G_BEGIN_DECLS

/**
 * crispy_profiler_get_flags:
 *
 * Returns the compiler flags needed for profiling instrumentation.
 *
 * Returns: (transfer none): the profiling flags string ("-pg")
 */
const gchar *crispy_profiler_get_flags (void);

/**
 * crispy_profiler_run_gprof:
 * @executable_path: path to the compiled executable
 * @gmon_path: (nullable): path to gmon.out, or %NULL for current directory
 * @output: (out) (transfer full): gprof output text
 * @error: return location for a #GError, or %NULL
 *
 * Runs gprof on the executable and captures the profiling output.
 *
 * Returns: %TRUE on success
 */
gboolean crispy_profiler_run_gprof (const gchar  *executable_path,
                                    const gchar  *gmon_path,
                                    gchar       **output,
                                    GError      **error);

/**
 * crispy_profiler_cleanup:
 * @gmon_path: (nullable): path to gmon.out to remove, or %NULL for "gmon.out"
 *
 * Removes the gmon.out file generated by profiling.
 */
void crispy_profiler_cleanup (const gchar *gmon_path);

G_END_DECLS

#endif /* CRISPY_PROFILER_PRIVATE_H */
